version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: house-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app         # <-- mount local code for hot-reloading
      - ./models:/app/models
    command: uvicorn FastAPI:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: house-ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/predict
    depends_on:
      - api
    volumes:
      - ./api:/app         # <-- mount local code for hot-reloading
    command: streamlit run app_streamlit.py --server.port=8501 --server.address=0.0.0.0
